import { defineConfig } from 'tsup';

export default defineConfig({
  entry: {
    'index': 'src/index.ts',
    'types/index': 'src/types/index.ts',
    'clock/index': 'src/clock/index.ts',
    'financial/index': 'src/financial/index.ts',
    'accounting/index': 'src/accounting/index.ts',
    'customer-funnel/index': 'src/customer-funnel/index.ts',
    'game-blueprints/index': 'src/game-blueprints/index.ts',
    'game-generator/index': 'src/game-generator/index.ts',
    'sim-harness/index': 'src/sim-harness/index.ts',
    'integration-recipes/index': 'src/integration-recipes/index.ts',
    'ui-blueprints/index': 'src/ui-blueprints/index.ts',
    'research-blueprint/index': 'src/research-blueprint/index.ts',
    'market/index': 'src/market/index.ts',
    'market-engine/index': 'src/market-engine/index.ts',
    'research/index': 'src/research/index.ts',
    'product/index': 'src/product/index.ts',
    'competitor/index': 'src/competitor/index.ts',
    'infrastructure/index': 'src/infrastructure/index.ts',
    'newspaper/index': 'src/newspaper/index.ts',
    'scoring/index': 'src/scoring/index.ts',
    'tick/index': 'src/tick/index.ts',
    'utils/index': 'src/utils/index.ts',
    'save-system/index': 'src/save-system/index.ts',
    // v0.1-alpha additions
    'inflation/index': 'src/inflation/index.ts',
    'press/index': 'src/press/index.ts',
    'competition/index': 'src/competition/index.ts',
    'market-topology/segmented/index': 'src/market-topology/segmented/index.ts',
    'perks/index': 'src/perks/index.ts',
    'revenue-models/unit-sale/index': 'src/revenue-models/unit-sale/index.ts',
    'events/index': 'src/events/index.ts',
    'competition/competitor/index': 'src/competition/competitor/index.ts',
    'competition/recognition/index': 'src/competition/recognition/index.ts',
    'competition/auction/index': 'src/competition/auction/index.ts',
    'asset-models/inventory/index': 'src/asset-models/inventory/index.ts',
    'reputation/index': 'src/reputation/index.ts',
    'seasonality/index': 'src/seasonality/index.ts',
    'market-topology/geographic/index': 'src/market-topology/geographic/index.ts',
    // v0.2 additions — lifted from ai-tycoon mechanics study
    'market-topology/product-competition/index': 'src/market-topology/product-competition/index.ts',
    'market-topology/use-case-matrix/index': 'src/market-topology/use-case-matrix/index.ts',
    'competition/acquisitions/index': 'src/competition/acquisitions/index.ts',
    'competition/licensing/index': 'src/competition/licensing/index.ts',
    'competition/capability-vectors/index': 'src/competition/capability-vectors/index.ts',
    'competition/company-sim/index': 'src/competition/company-sim/index.ts',
    'competition/rival-sim/index': 'src/competition/rival-sim/index.ts',
    'competition/rival-adapters/index': 'src/competition/rival-adapters/index.ts',
    'asset-models/multi-tier-production/index': 'src/asset-models/multi-tier-production/index.ts',
    'asset-models/rights/index': 'src/asset-models/rights/index.ts',
    'asset-models/fleet/index': 'src/asset-models/fleet/index.ts',
    'asset-models/infrastructure/index': 'src/asset-models/infrastructure/index.ts',
    'revenue-models/subscription/index': 'src/revenue-models/subscription/index.ts',
    'revenue-models/transaction/index': 'src/revenue-models/transaction/index.ts',
    'market-topology/network/index': 'src/market-topology/network/index.ts',
    'marketplace/index': 'src/marketplace/index.ts',
    'balance-sheet/index': 'src/balance-sheet/index.ts',
    // v0.2 additions — Stream Co. enablers
    'revenue-models/ads/index': 'src/revenue-models/ads/index.ts',
    'revenue-models/pricing/index': 'src/revenue-models/pricing/index.ts',
    'pipeline/index': 'src/pipeline/index.ts',
    'engagement/index': 'src/engagement/index.ts',
    'content-slate/index': 'src/content-slate/index.ts',
    // alpha.25 additions — Sahyadri Air enablers
    'commodities/index': 'src/commodities/index.ts',
    'loyalty/index': 'src/loyalty/index.ts',
    'perishable/index': 'src/perishable/index.ts',
  },
  format: ['esm', 'cjs'],
  dts: true,
  clean: true,
  splitting: false,
});
