export const DAYS_PER_WEEK = 7;
export const WEEKS_PER_QUARTER = 13;
export const QUARTERS_PER_YEAR = 4;
export const DAYS_PER_QUARTER = DAYS_PER_WEEK * WEEKS_PER_QUARTER; // 91
export const DAYS_PER_YEAR = DAYS_PER_QUARTER * QUARTERS_PER_YEAR; // 364
export const DAYS_PER_MONTH = 30;
